spring:
  application:
    name: start	
  datasource:
    url: jdbc:oracle:thin:@115.90.212.20:10000:XE
    username: BJY11
    password: BJY111234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  
server:
   port:  8081
 
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==